import os as os

print('--------------------------')
print('- Windows 11 Tweaks V1.0 -')
print('--------------------------')

Menus = input('¿Habilitar los Menús Contextuales Clásicos? (Y/N): ')
if Menus == 'Y':
    os.system('REG ADD "HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32" -F')

Edge = input('¿Ajustes Personalizados de Microsoft Edge? (Y/N): ')
if Edge == 'Y':
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V AutofillAddressEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V AutofillCreditCardEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V BrowserAddProfileEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V BrowserSignin -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V EdgeCollectionsEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V EdgeShoppingAssistantEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V PasswordManagerEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V PaymentMethodQueryEnabled -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V ShowMicrosoftRewards -T REG_DWORD -D 0 -F')
    os.system('REG ADD "HKCU\Software\Policies\Microsoft\Edge" -V VerticalTabsAllowed -T REG_DWORD -D 0 -F')

print('Desinstalando las Aplicaciones...')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.WindowsAlarms* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.XboxGamingOverlay* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.WindowsCamera* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.WindowsFeedbackHub* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.BingNews* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.Todo* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.People* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.BingWeather* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.WindowsSoundRecorder* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *MicrosoftTeams* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.ZuneMusic* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.WindowsMaps* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.GetHelp* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.ZuneVideo* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.Getstarted* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.YourPhone* | Remove-AppxPackage"')
os.system('PowerShell -Command "Get-AppxPackage *Microsoft.549981C3F5F10* | Remove-AppxPackage"')
print('Aplicaciones Desinstaladas')
print('Desinstalando OneDrive')
os.system('%WINDIR%\SysWOW64\OneDriveSetup.exe /Uninstall')
print('Eliminando la Carpeta de OneDrive')
os.system('RD /Q /S "%ONEDRIVE%"')
print('Eliminando la Carpeta de Juegos Guardados')
os.system('RD /Q /S "%USERPROFILE%\Saved Games"')
print('Desactivando la Suspensión del Sistema')
os.system('PowerCFG -Change STANDBY-TIMEOUT-AC 0')
print('Aplicando la Configuración del Registro')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -V TaskbarMn -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\SearchSettings" -V IsDeviceSearchHistoryEnabled -T REG_DWORD -D 0 -F')
os.system(r'REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" -V ScoobeSystemSettingEnabled -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -V SubscribedContent-338389Enabled -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers" -V DisableAutoplay -T REG_DWORD -D 1 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -V Start_TrackDocs -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer" -V ShowFrequent -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -V SubscribedContent-338393Enabled -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -V SubscribedContent-353694Enabled -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -V SubscribedContent-353696Enabled -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\DWM" -V ColorPrevalence -T REG_DWORD -D 1 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -V VisualFXSetting -T REG_DWORD -D 3 -F')
os.system('REG ADD "HKCU\Control Panel\Desktop\WindowMetrics" -V MinAnimate -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\DWM" -V EnableAeroPeek -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Control Panel\Desktop" -V UserPreferencesMask -T REG_BINARY -D 9012078010000000 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -V TaskbarAnimations -T REG_DWORD -D 0 -F')
os.system('REG ADD "HKCU\Control Panel\Desktop" -V DragFullWindows -D 0 -F')
os.system('REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -V ListviewAlphaSelect -T REG_DWORD -D 0 -F')
os.system('REG DELETE "HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount" /F')
print('Todos los Cambios Realizados')
Reiniciar = input('¿Reiniciar el Sistema al Salir? (Y/N): ')
if Reiniciar == 'Y':
    os.system('Shutdown /R /T 5')
    exit()
else:
    exit()